import { useEffect, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Pencil, Plus, Trash2, Users } from "lucide-react"
import api from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { useToast } from "@/components/ui/toast"

interface Member { id: number; user_id: number; role: string; status: string; user?: { username?: string; email?: string } }
interface Department { id: number; name: string; slug: string; parent_id?: number }
interface UserAccount { id: number; username: string; email: string; balance: string | number; group_id?: number; is_admin: boolean }
interface Employee extends UserAccount { member?: Member }

export default function EnterprisePeopleManagement() {
  const [tab, setTab] = useState<"members" | "departments">("members")
  const [employee, setEmployee] = useState<Employee | null>(null)
  const [department, setDepartment] = useState<Department | null>(null)
  const queryClient = useQueryClient()
  const { success, error } = useToast()
  const members = useQuery<{ members: Member[] }>({ queryKey: ["enterprise-members"], queryFn: async () => (await api.get("/user/enterprise/members")).data })
  const users = useQuery<UserAccount[]>({ queryKey: ["users"], queryFn: async () => { const response = await api.get("/users"); return Array.isArray(response.data) ? response.data : [] } })
  const departments = useQuery<{ departments: Department[] }>({ queryKey: ["enterprise-departments"], queryFn: async () => (await api.get("/user/enterprise/departments")).data })
  const memberDepartments = useQuery<{ department_ids: number[] }>({ queryKey: ["enterprise-member-departments", employee?.id], enabled: Boolean(employee?.id), queryFn: async () => (await api.get(`/user/enterprise/members/${employee?.id}/departments`)).data })
  const refreshMembers = () => queryClient.invalidateQueries({ queryKey: ["enterprise-members"] })
  const refreshDepartments = () => queryClient.invalidateQueries({ queryKey: ["enterprise-departments"] })
  const saveEmployee = useMutation({ mutationFn: async ({ user, role, status, departmentIDs }: { user: Employee; role: string; status: string; departmentIDs: number[] }) => {
    await api.put(`/users/${user.id}`, { balance: Number(user.balance || 0), group_id: user.group_id || 0, is_admin: user.is_admin })
    await api.patch(`/user/enterprise/members/${user.id}`, { role, status })
    await api.put(`/user/enterprise/members/${user.id}/departments`, { department_ids: departmentIDs })
  }, onSuccess: () => { setEmployee(null); void refreshMembers(); void queryClient.invalidateQueries({ queryKey: ["users"] }); success("员工账户与成员信息已更新") }, onError: () => error("更新员工失败") })
  const saveDepartment = useMutation({ mutationFn: ({ id, body }: { id?: number; body: object }) => id ? api.put(`/user/enterprise/departments/${id}`, body) : api.post("/user/enterprise/departments", body), onSuccess: () => { setDepartment(null); void refreshDepartments(); success("部门已保存") }, onError: () => error("保存部门失败") })
  const deleteDepartment = useMutation({ mutationFn: (id: number) => api.delete(`/user/enterprise/departments/${id}`), onSuccess: () => { void refreshDepartments(); success("部门已删除") }, onError: () => error("删除部门失败") })
  return <div className="space-y-5">
    <div><div className="flex items-center gap-2"><Users className="h-5 w-5 text-primary" /><h1 className="text-2xl font-semibold">员工管理</h1></div><p className="mt-1 text-sm text-muted-foreground">员工就是系统用户。企业角色、状态和部门只是同一用户账户在企业内的附加关系。</p></div>
    <div className="flex w-fit gap-1 rounded-md border bg-muted/40 p-1"><button className={`rounded px-3 py-2 text-sm ${tab === "members" ? "bg-background font-medium shadow-sm" : "text-muted-foreground"}`} onClick={() => setTab("members")}>成员管理</button><button className={`rounded px-3 py-2 text-sm ${tab === "departments" ? "bg-background font-medium shadow-sm" : "text-muted-foreground"}`} onClick={() => setTab("departments")}>部门管理</button></div>
    {tab === "members" ? <div className="space-y-2">{users.data?.filter((user) => !isPoolAccount(user)).length ? users.data.filter((user) => !isPoolAccount(user)).map((user) => { const member = members.data?.members.find((item) => item.user_id === user.id); return <div key={user.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-4"><div><div className="font-medium">{user.username || user.email}</div><div className="mt-1 text-xs text-muted-foreground">用户 ID {user.id} · 余额 {user.balance} · {member ? `${member.role} · ${member.status}` : "未加入企业"}</div></div><Button size="sm" variant="outline" disabled={!member} onClick={() => setEmployee({ ...user, member })}><Pencil className="mr-1 h-4 w-4" />编辑</Button></div> }) : <Empty text="暂无员工。" />}</div> : <><div className="flex justify-end"><Button size="sm" onClick={() => setDepartment({ id: 0, name: "", slug: "" })}><Plus className="mr-1 h-4 w-4" />新建部门</Button></div><div className="mt-3 space-y-2">{departments.data?.departments?.length ? departments.data.departments.map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border p-4"><div><div className="font-medium">{item.name}</div><div className="text-xs text-muted-foreground">{item.slug}</div></div><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="编辑部门" onClick={() => setDepartment(item)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label="删除部门" disabled={deleteDepartment.isPending} onClick={() => deleteDepartment.mutate(item.id)}><Trash2 className="h-4 w-4" /></Button></div></div>) : <Empty text="暂无部门。" />}</div></>}
    <EmployeeDialog employee={employee} departments={departments.data?.departments || []} departmentIDs={memberDepartments.data?.department_ids} pending={saveEmployee.isPending} onClose={() => setEmployee(null)} onSave={(user, role, status, departmentIDs) => saveEmployee.mutate({ user, role, status, departmentIDs })} />
    <DepartmentDialog department={department} departments={departments.data?.departments || []} pending={saveDepartment.isPending} onClose={() => setDepartment(null)} onSave={(body) => saveDepartment.mutate({ id: department?.id || undefined, body })} />
  </div>
}
function EmployeeDialog({ employee, departments, departmentIDs, pending, onClose, onSave }: { employee: Employee | null; departments: Department[]; departmentIDs?: number[]; pending: boolean; onClose: () => void; onSave: (user: Employee, role: string, status: string, departmentIDs: number[]) => void }) { const [role, setRole] = useState("member"), [status, setStatus] = useState("active"), [balance, setBalance] = useState(""), [selectedDepartments, setSelectedDepartments] = useState<number[]>([]); useEffect(() => { setRole(employee?.member?.role || "member"); setStatus(employee?.member?.status || "active"); setBalance(String(employee?.balance ?? 0)); if (departmentIDs) setSelectedDepartments(departmentIDs) }, [employee, departmentIDs]); const toggleDepartment = (id: number) => setSelectedDepartments((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); return <Dialog open={Boolean(employee)} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>编辑员工账户</DialogTitle></DialogHeader><div className="space-y-3"><Input disabled value={employee?.username || ""} /><Input disabled value={employee?.email || ""} /><Input type="number" step="0.000001" value={balance} onChange={(event) => setBalance(event.target.value)} placeholder="个人余额" /><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={role} onChange={(event) => setRole(event.target.value)}><option value="owner">所有者</option><option value="admin">企业管理员</option><option value="member">员工</option><option value="auditor">审计员</option></select><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value)}><option value="active">在职</option><option value="suspended">已停用</option><option value="invited">待激活</option></select><div className="space-y-2"><div className="text-sm font-medium">所属部门</div>{departments.length ? departments.map((department) => <label key={department.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selectedDepartments.includes(department.id)} onChange={() => toggleDepartment(department.id)} />{department.name}</label>) : <p className="text-sm text-muted-foreground">暂无部门。</p>}</div></div><DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button disabled={pending} onClick={() => employee && onSave({ ...employee, balance }, role, status, selectedDepartments)}>保存</Button></DialogFooter></DialogContent></Dialog> }
function DepartmentDialog({ department, departments, pending, onClose, onSave }: { department: Department | null; departments: Department[]; pending: boolean; onClose: () => void; onSave: (body: object) => void }) { const [name, setName] = useState(""), [slug, setSlug] = useState(""), [parent, setParent] = useState(""); useEffect(() => { setName(department?.name || ""); setSlug(department?.slug || ""); setParent(String(department?.parent_id || "")) }, [department]); return <Dialog open={Boolean(department)} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{department?.id ? "编辑部门" : "新建部门"}</DialogTitle></DialogHeader><div className="space-y-3"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="部门名称" /><Input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="部门标识" /><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={parent} onChange={(event) => setParent(event.target.value)}><option value="">无上级部门</option>{departments.filter((item) => item.id !== department?.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button disabled={pending || !name.trim() || !slug.trim()} onClick={() => onSave({ name, slug, parent_id: parent ? Number(parent) : undefined })}>保存</Button></DialogFooter></DialogContent></Dialog> }
function Empty({ text }: { text: string }) { return <div className="rounded-md border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div> }
function isPoolAccount(user: UserAccount) { return user.username.startsWith("enterprise-pool-") || user.email.endsWith("@internal.invalid") }
