import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import type { ReactNode } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Building2, Copy, Pencil, Plus, Terminal, Trash2 } from "lucide-react"
import api from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { useToast } from "@/components/ui/toast"
import { TabTransition } from "@/components/layout/TabTransition"

interface Organization { id: number; name: string; slug: string; status: string; description?: string }
interface Member { id: number; user_id: number; role: string; status: string; user?: { username?: string; email?: string } }
interface Department { id: number; name: string; slug: string; parent_id?: number }
interface User { id: number; username?: string; email?: string }
interface Task { id: number; title: string; description: string; status: string; owner_user_id: number; owner?: User }
interface Role { id: number; name: string; slug: string; builtin: boolean; description?: string; permissions?: string[] }
interface Permission { code: string; resource: string; action: string; description: string }
interface RoleBinding { id: number; user_id: number; role_id: number; scope_type: string; scope_id: number; role?: Role; user?: User }
interface Device { id: number; name: string; external_device_id: string; status: string; kind: string; online?: boolean; hostname?: string; os?: string; last_seen_at?: string }
interface ConnectorCommand { token: string; device: Device; mode: "platform" | "web_server"; listen_port?: number }
interface Assignment { id: number; device_id: number; scope_type: string; user_id?: number; task_id?: number; status: string }
interface QuotaAccount { id: number; scope_type: string; scope_key: string; pool_id?: number; limit_amount: string; reserved_amount: string; consumed_amount: string }
interface SharedPool { id: number; scope_type: "task" | "department"; scope_key: string; name: string; task_id?: number; department_id?: number }
interface PersonalResource { id: string; title?: string; name?: string; updated_at?: string }
type DialogKind = "organization" | "member" | "department" | "task" | "device" | "command" | "pool" | "share-resource" | "assignment" | "quota" | "allocation" | "reclaim" | "grant" | "role" | "binding" | null

const selectClass = "h-10 w-full rounded-md border bg-background px-3 text-sm"

export default function EnterpriseManagement() {
  const [activeTab, setActiveTab] = useState<EnterpriseTab>("organization")
  const [dialog, setDialog] = useState<DialogKind>(null)
  const [editingMember, setEditingMember] = useState<Member | null>(null)
  const [editingDepartment, setEditingDepartment] = useState<Department | null>(null)
  const [connectorCommand, setConnectorCommand] = useState<ConnectorCommand | null>(null)
  const [selectedPool, setSelectedPool] = useState<SharedPool | null>(null)
  const [editingRole, setEditingRole] = useState<Role | null>(null)
  const queryClient = useQueryClient()
  const { success, error } = useToast()
  const organization = useQuery<{ organization: Organization }>({ queryKey: ["enterprise-organization"], queryFn: async () => (await api.get("/user/enterprise/organization")).data })
  const members = useQuery<{ members: Member[] }>({ queryKey: ["enterprise-members"], queryFn: async () => (await api.get("/user/enterprise/members")).data, retry: false })
  const departments = useQuery<{ departments: Department[] }>({ queryKey: ["enterprise-departments"], queryFn: async () => (await api.get("/user/enterprise/departments")).data, retry: false })
  const roles = useQuery<{ roles: Role[] }>({ queryKey: ["enterprise-roles"], queryFn: async () => (await api.get("/user/enterprise/roles")).data, retry: false })
  const permissions = useQuery<{ permissions: Permission[] }>({ queryKey: ["enterprise-permissions"], queryFn: async () => (await api.get("/user/enterprise/permissions")).data, retry: false })
  const bindings = useQuery<{ bindings: RoleBinding[] }>({ queryKey: ["enterprise-role-bindings"], queryFn: async () => (await api.get("/user/enterprise/role-bindings")).data, retry: false })
  const tasks = useQuery<{ tasks: Task[] }>({ queryKey: ["enterprise-managed-tasks"], queryFn: async () => (await api.get("/user/enterprise/managed-tasks")).data, retry: false })
  const devices = useQuery<{ devices: Device[] }>({ queryKey: ["enterprise-devices"], queryFn: async () => (await api.get("/user/enterprise/devices")).data, retry: false })
  const assignments = useQuery<{ assignments: Assignment[] }>({ queryKey: ["enterprise-device-assignments"], queryFn: async () => (await api.get("/user/enterprise/device-assignments")).data, retry: false })
  const quotas = useQuery<{ accounts: QuotaAccount[] }>({ queryKey: ["enterprise-quota-accounts"], queryFn: async () => (await api.get("/user/enterprise/quota-accounts")).data, retry: false })
  const sharedPools = useQuery<{ pools: SharedPool[] }>({ queryKey: ["enterprise-shared-pools"], queryFn: async () => (await api.get("/user/enterprise/shared-pools")).data, retry: false })
  const personalSessions = useQuery<PersonalResource[]>({ queryKey: ["personal-advanced-chat-sessions"], queryFn: async () => { const response = await api.get("/user/advanced-chat/sessions"); return Array.isArray(response.data) ? response.data : [] }, retry: false })
  const personalFiles = useQuery<{ files: PersonalResource[] }>({ queryKey: ["personal-advanced-chat-files"], queryFn: async () => (await api.get("/user/advanced-chat/files")).data, retry: false })
  const invalidate = (keys: string[]) => Promise.all(keys.map((key) => queryClient.invalidateQueries({ queryKey: [key] })))
  const saveMember = useMutation({ mutationFn: ({ userID, body }: { userID: number; body: object }) => api.patch(`/user/enterprise/members/${userID}`, body), onSuccess: async () => { await invalidate(["enterprise-members"]); closeDialog(); success("员工信息已更新") }, onError: showError })
  const saveOrganization = useMutation({ mutationFn: (body: object) => api.put("/user/enterprise/organization", body), onSuccess: async () => { await invalidate(["enterprise-organization"]); closeDialog(); success("企业资料已更新") }, onError: showError })
  const saveDepartment = useMutation({ mutationFn: ({ id, body }: { id?: number; body: object }) => id ? api.put(`/user/enterprise/departments/${id}`, body) : api.post("/user/enterprise/departments", body), onSuccess: async () => { await invalidate(["enterprise-departments"]); closeDialog(); success("部门已保存") }, onError: showError })
  const deleteDepartment = useMutation({ mutationFn: (id: number) => api.delete(`/user/enterprise/departments/${id}`), onSuccess: async () => { await invalidate(["enterprise-departments"]); success("部门已删除") }, onError: showError })
  const createTask = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/tasks", body), onSuccess: async () => { await invalidate(["enterprise-managed-tasks"]); closeDialog(); success("任务已分派") }, onError: showError })
  const createDevice = useMutation({ mutationFn: (body: object) => api.post<ConnectorCommand>("/user/enterprise/devices/connector-command", body), onSuccess: async (response) => { await invalidate(["enterprise-devices"]); setConnectorCommand(response.data); setDialog("command"); success("连接命令已生成") }, onError: showError })
  const rotateDeviceCommand = useMutation({ mutationFn: (id: number) => api.post<ConnectorCommand>(`/user/enterprise/devices/${id}/connector-command`), onSuccess: async (response) => { await invalidate(["enterprise-devices"]); setConnectorCommand(response.data); setDialog("command"); success("连接命令已重新生成") }, onError: showError })
  const createAssignment = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/device-assignments", body), onSuccess: async () => { await invalidate(["enterprise-device-assignments"]); closeDialog(); success("设备已分配") }, onError: showError })
  const revokeAssignment = useMutation({ mutationFn: (id: number) => api.post(`/user/enterprise/device-assignments/${id}/revoke`), onSuccess: async () => { await invalidate(["enterprise-device-assignments"]); success("设备分配已撤销") }, onError: showError })
  const createQuota = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/quota-accounts", body), onSuccess: async () => { await invalidate(["enterprise-quota-accounts"]); closeDialog(); success("额度账户已创建") }, onError: showError })
  const createSharedPool = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/shared-pools", body), onSuccess: async () => { await invalidate(["enterprise-shared-pools"]); closeDialog(); success("共享池已创建") }, onError: showError })
  const sharePoolResource = useMutation({ mutationFn: ({ poolID, type, id }: { poolID: number; type: "sessions" | "files"; id: string }) => api.post(`/user/enterprise/shared-pools/${poolID}/${type}`, { id }), onSuccess: () => { closeDialog(); success("资源已加入共享池") }, onError: showError })
  const allocateQuota = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/quota-allocations", body), onSuccess: async () => { await invalidate(["enterprise-quota-accounts"]); closeDialog(); success("额度已下拨") }, onError: showError })
  const reclaimQuota = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/pools/organization-budget/reclaim", body), onSuccess: async () => { await invalidate(["enterprise-quota-accounts"]); closeDialog(); success("预算已回收至组织") }, onError: showError })
  const grantBudget = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/user-budgets", body), onSuccess: async () => { await invalidate(["enterprise-quota-accounts", "enterprise-members"]); closeDialog(); success("组织预算已发放给员工") }, onError: showError })
  const createRole = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/roles", body), onSuccess: async () => { await invalidate(["enterprise-roles"]); closeDialog(); success("角色已创建") }, onError: showError })
  const updateRole = useMutation({ mutationFn: ({ id, body }: { id: number; body: object }) => api.put(`/user/enterprise/roles/${id}`, body), onSuccess: async () => { await invalidate(["enterprise-roles"]); closeDialog(); success("权限组已更新") }, onError: showError })
  const createBinding = useMutation({ mutationFn: (body: object) => api.post("/user/enterprise/role-bindings", body), onSuccess: async () => { await invalidate(["enterprise-role-bindings"]); closeDialog(); success("角色已授权") }, onError: showError })
  const deleteBinding = useMutation({ mutationFn: (id: number) => api.delete(`/user/enterprise/role-bindings/${id}`), onSuccess: async () => { await invalidate(["enterprise-role-bindings"]); success("角色授权已撤销") }, onError: showError })
  function showError(err: unknown) { error(apiError(err)) }
  function closeDialog() { setDialog(null); setEditingMember(null); setEditingDepartment(null); setEditingRole(null); setConnectorCommand(null); setSelectedPool(null) }
  const memberList = members.data?.members || [], taskList = tasks.data?.tasks || [], deviceList = devices.data?.devices || [], accountList = quotas.data?.accounts || []
  const tabs: { id: EnterpriseTab; label: string }[] = [{ id: "organization", label: "组织" }, { id: "tasks", label: "任务" }, { id: "pools", label: "共享会话与文件" }, { id: "devices", label: "设备与连接器" }, { id: "quota", label: "组织预算" }, { id: "security", label: "安全权限" }]
  return <div className="space-y-5">
    <div><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-primary" /><h1 className="text-2xl font-semibold">企业管理</h1></div><p className="mt-1 text-sm text-muted-foreground">{organization.data?.organization ? `${organization.data.organization.name} · ${organization.data.organization.status}` : "加载企业配置..."}</p></div>
    <div className="flex gap-2 overflow-x-auto border-b pb-2">{tabs.map((tab) => <Button key={tab.id} type="button" variant={activeTab === tab.id ? "default" : "outline"} className="shrink-0" onClick={() => setActiveTab(tab.id)}>{tab.label}</Button>)}</div>
    <TabTransition activeKey={activeTab} order={tabs.map((tab) => tab.id)}>
    {activeTab === "organization" && <Section title="组织配置" description="企业资料与数据分类边界。首页概览可直接进入可视化编辑，添加组件后即为企业门户。"><div className="mb-4 flex gap-2"><HeaderAction label="编辑企业资料" onClick={() => setDialog("organization")} /></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="企业名称" value={organization.data?.organization.name || "-"} /><Metric label="企业标识" value={organization.data?.organization.slug || "-"} /><Metric label="状态" value={organization.data?.organization.status || "-"} /></div>{organization.data?.organization.description && <p className="mt-4 text-sm text-muted-foreground">{organization.data.organization.description}</p>}</Section>}
    {activeTab === "members" && <Section title="员工与部门" description="员工负责操作、任务协作和授权；资源与额度由部门、任务池统一承载。"><div className="space-y-2">{memberList.length ? memberList.map((member) => <div key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3"><div><div className="font-medium">{memberName(member)}</div><div className="text-xs text-muted-foreground">员工 ID {member.user_id} · {member.role} · {member.status}</div></div><Button variant="outline" size="sm" onClick={() => { setEditingMember(member); setDialog("member") }}><Pencil className="mr-1 h-4 w-4" />编辑</Button></div>) : <Empty text="尚无可查看的员工数据。" />}</div><div className="mt-5 flex items-center justify-between"><h3 className="font-medium">部门</h3><HeaderAction label="新建部门" onClick={() => setDialog("department")} /></div><div className="mt-2 space-y-2">{departments.data?.departments?.length ? departments.data.departments.map((department) => <div key={department.id} className="flex items-center justify-between rounded-md border p-3"><span className="text-sm">{department.name} · {department.slug}</span><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="编辑部门" onClick={() => { setEditingDepartment(department); setDialog("department") }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label="删除部门" disabled={deleteDepartment.isPending} onClick={() => deleteDepartment.mutate(department.id)}><Trash2 className="h-4 w-4" /></Button></div></div>) : <Empty text="尚未创建部门。" />}</div></Section>}
    {activeTab === "tasks" && <Section title="任务与分派" description="每个任务自动创建唯一的内置资源池；负责人、执行人和参与人在自己的工作台协作。"><HeaderAction label="新建并分派任务" onClick={() => setDialog("task")} /><div className="grid gap-4 sm:grid-cols-3"><Metric label="企业任务" value={String(taskList.length)} /><Metric label="执行中" value={String(taskList.filter((task) => task.status === "running").length)} /><Metric label="已分派" value={String(taskList.filter((task) => task.status === "assigned").length)} /></div><div className="mt-4 space-y-2">{taskList.length ? taskList.map((task) => <div key={task.id} className="flex items-center justify-between rounded-md border p-3"><Link className="font-medium hover:underline" to={`/dashboard/enterprise/tasks/${task.id}?managed=1`}>#{task.id} · {task.title}</Link><span className="text-xs text-muted-foreground">{task.status} · 负责人 {userName(task.owner, task.owner_user_id)}</span></div>) : <Empty text={tasks.isError ? "没有任务管理权限。" : "暂无任务。"} />}</div></Section>}
    {activeTab === "pools" && <Section title="共享会话与文件池" description="每个任务都自动拥有且仅拥有一个内置任务池。这里仅可创建部门池；个人会话和文件进入池后保留来源和审计记录。"><HeaderAction label="创建部门池" onClick={() => setDialog("pool")} /><div className="mt-4 space-y-2">{sharedPools.data?.pools?.length ? sharedPools.data.pools.map((pool) => <div key={pool.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3"><div><div className="font-medium">{pool.name}</div><div className="text-xs text-muted-foreground">{pool.scope_type === "task" ? "任务内置" : "部门"}池 · {pool.scope_key}</div></div><Button size="sm" variant="outline" onClick={() => { setSelectedPool(pool); setDialog("share-resource") }}>共享我的资源</Button></div>) : <Empty text="尚无可访问的共享池。创建任务后会自动生成唯一的任务池。" />}</div></Section>}
    {activeTab === "devices" && <Section title="设备与连接器" description="生成连接命令后，在目标设备运行连接器；在线状态会自动同步。"><div className="mb-4 flex flex-wrap gap-2"><HeaderAction label="生成连接命令" onClick={() => setDialog("device")} /><HeaderAction label="分配设备" onClick={() => setDialog("assignment")} /></div><div className="space-y-2">{deviceList.length ? deviceList.map((device) => <div key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3"><div><div className="font-medium">{device.name}</div><div className="text-xs text-muted-foreground">{device.online ? "在线" : "离线"} · {device.hostname || device.os || device.external_device_id}</div></div><Button size="sm" variant="outline" disabled={rotateDeviceCommand.isPending} onClick={() => rotateDeviceCommand.mutate(device.id)}><Terminal className="mr-1 h-4 w-4" />重新生成命令</Button></div>) : <Empty text="暂无企业连接器，先生成连接命令。" />}</div><div className="mt-5 space-y-2">{assignments.data?.assignments?.map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border p-3"><span className="text-sm">设备 #{item.device_id} → {item.scope_type} · {item.status}</span>{item.status === "active" && <Button size="sm" variant="outline" disabled={revokeAssignment.isPending} onClick={() => revokeAssignment.mutate(item.id)}>撤销</Button>}</div>)}</div></Section>}
    {activeTab === "quota" && <Section title="组织预算" description="组织预算可下拨到任务池、从池回收，或发放给员工；员工个人余额仅可自行投入任务池，不能从池中取回。"><div className="mb-4 flex flex-wrap gap-2"><HeaderAction label="添加组织预算" onClick={() => setDialog("quota")} /><HeaderAction label="组织预算下拨到池" onClick={() => setDialog("allocation")} /><HeaderAction label="从池回收预算" onClick={() => setDialog("reclaim")} /><HeaderAction label="发放给员工" onClick={() => setDialog("grant")} /></div><div className="space-y-2">{accountList.length ? accountList.map((account) => <Row key={account.id} title={`#${account.id} · ${account.scope_type} · ${account.scope_key}`} detail={`预算 ${account.limit_amount} / 预留 ${account.reserved_amount} / 消耗 ${account.consumed_amount}`} />) : <Empty text="尚未添加组织预算。" />}</div></Section>}
    {activeTab === "security" && <Section title="安全与权限" description="角色定义、细粒度权限和员工范围授权。"><div className="mb-4 flex gap-2"><HeaderAction label="新建权限组" onClick={() => setDialog("role")} /><HeaderAction label="授予角色" onClick={() => setDialog("binding")} /></div><div className="space-y-2">{roles.data?.roles.map((role) => <div key={role.id} className="flex items-center justify-between rounded-md border p-3"><div><div className="font-medium">{role.name}</div><div className="text-xs text-muted-foreground">{role.slug} · {role.permissions?.length || 0} 项权限 · {role.builtin ? "预置角色" : "自定义权限组"}</div></div>{!role.builtin && <Button size="sm" variant="outline" onClick={() => { setEditingRole(role); setDialog("role") }}><Pencil className="mr-1 h-4 w-4" />编辑</Button>}</div>)}</div><div className="mt-5 space-y-2">{bindings.data?.bindings?.map((binding) => <div key={binding.id} className="flex items-center justify-between rounded-md border p-3"><span className="text-sm">{binding.role?.name || `角色 #${binding.role_id}`} → {userName(binding.user, binding.user_id)} · {binding.scope_type}</span><Button size="icon" variant="ghost" aria-label="撤销角色" disabled={deleteBinding.isPending} onClick={() => deleteBinding.mutate(binding.id)}><Trash2 className="h-4 w-4" /></Button></div>)}</div></Section>}
    </TabTransition>
    <MemberDialog open={dialog === "member"} member={editingMember} pending={saveMember.isPending} onClose={closeDialog} onSave={(body) => editingMember && saveMember.mutate({ userID: editingMember.user_id, body })} />
    <OrganizationDialog open={dialog === "organization"} organization={organization.data?.organization} pending={saveOrganization.isPending} onClose={closeDialog} onSave={(body) => saveOrganization.mutate(body)} />
    <TaskDialog open={dialog === "task"} members={memberList} pending={createTask.isPending} onClose={closeDialog} onSave={(body) => createTask.mutate(body)} />
    <DeviceDialog open={dialog === "device"} members={memberList} pending={createDevice.isPending} onClose={closeDialog} onSave={(body) => createDevice.mutate(body)} />
    <ConnectorCommandDialog open={dialog === "command"} command={connectorCommand} onClose={closeDialog} />
    <SharedPoolDialog open={dialog === "pool"} tasks={taskList} departments={departments.data?.departments || []} pending={createSharedPool.isPending} onClose={closeDialog} onSave={(body) => createSharedPool.mutate(body)} />
    <ShareResourceDialog open={dialog === "share-resource"} pool={selectedPool} sessions={personalSessions.data || []} files={personalFiles.data?.files || []} pending={sharePoolResource.isPending} onClose={closeDialog} onSave={(type, id) => selectedPool && sharePoolResource.mutate({ poolID: selectedPool.id, type, id })} />
    <DepartmentDialog open={dialog === "department"} department={editingDepartment} departments={departments.data?.departments || []} pending={saveDepartment.isPending} onClose={closeDialog} onSave={(body) => saveDepartment.mutate({ id: editingDepartment?.id, body })} />
    <AssignmentDialog open={dialog === "assignment"} devices={deviceList} members={memberList} departments={departments.data?.departments || []} tasks={taskList} pending={createAssignment.isPending} onClose={closeDialog} onSave={(body) => createAssignment.mutate(body)} />
    <QuotaDialog open={dialog === "quota"} pending={createQuota.isPending} onClose={closeDialog} onSave={(body) => createQuota.mutate(body)} />
    <AllocationDialog open={dialog === "allocation"} accounts={accountList} pending={allocateQuota.isPending} onClose={closeDialog} onSave={(body) => allocateQuota.mutate(body)} />
    <PoolBudgetDialog open={dialog === "reclaim"} pools={accountList.filter((item) => item.scope_type === "pool")} pending={reclaimQuota.isPending} onClose={closeDialog} onSave={(body) => reclaimQuota.mutate(body)} title="从任务池回收组织预算" />
    <UserBudgetDialog open={dialog === "grant"} members={memberList} pending={grantBudget.isPending} onClose={closeDialog} onSave={(body) => grantBudget.mutate(body)} />
    <RoleDialog open={dialog === "role"} role={editingRole} permissions={permissions.data?.permissions || []} pending={createRole.isPending || updateRole.isPending} onClose={closeDialog} onSave={(body) => editingRole ? updateRole.mutate({ id: editingRole.id, body }) : createRole.mutate(body)} />
    <BindingDialog open={dialog === "binding"} members={memberList} roles={roles.data?.roles || []} pending={createBinding.isPending} onClose={closeDialog} onSave={(body) => createBinding.mutate(body)} />
  </div>
}

function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader>{children}</DialogContent></Dialog> }
function Footer({ pending, onClose, submit }: { pending: boolean; onClose: () => void; submit: () => void }) { return <DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button disabled={pending} onClick={submit}>{pending ? "提交中..." : "保存"}</Button></DialogFooter> }
function OrganizationDialog({ open, organization, pending, onClose, onSave }: DialogProps & { organization?: Organization }) { const [name, setName] = useState(""), [description, setDescription] = useState(""); useEffect(() => { setName(organization?.name || ""); setDescription(organization?.description || "") }, [organization, open]); return <Modal open={open} title="编辑企业资料" onClose={onClose}><div className="space-y-3"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="企业名称" /><textarea className="min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="企业简介" /></div><Footer pending={pending} onClose={onClose} submit={() => name.trim() && onSave({ name, description })} /></Modal> }
function MemberDialog({ open, member, pending, onClose, onSave }: { open: boolean; member: Member | null; pending: boolean; onClose: () => void; onSave: (body: object) => void }) { const [role, setRole] = useState("member"), [status, setStatus] = useState("active"); useEffect(() => { if (member) { setRole(member.role); setStatus(member.status) } }, [member]); return <Modal open={open} title={`编辑 ${member ? memberName(member) : "员工"}`} onClose={onClose}><div className="space-y-3"><select className={selectClass} value={role} onChange={(e) => setRole(e.target.value)}><option value="owner">所有者</option><option value="admin">企业管理员</option><option value="member">员工</option><option value="auditor">审计员</option></select><select className={selectClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="active">在职</option><option value="suspended">已停用</option><option value="invited">待激活</option></select></div><Footer pending={pending} onClose={onClose} submit={() => onSave({ role, status })} /></Modal> }
function DepartmentDialog({ open, department, departments, pending, onClose, onSave }: DialogProps & { department: Department | null; departments: Department[] }) { const [name, setName] = useState(""), [slug, setSlug] = useState(""), [parent, setParent] = useState(""); useEffect(() => { setName(department?.name || ""); setSlug(department?.slug || ""); setParent(String(department?.parent_id || "")) }, [department, open]); return <Modal open={open} title={department ? "编辑部门" : "新建部门"} onClose={onClose}><div className="space-y-3"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="部门名称" /><Input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="部门标识" /><select className={selectClass} value={parent} onChange={(e) => setParent(e.target.value)}><option value="">无上级部门</option>{departments.filter((item) => item.id !== department?.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><Footer pending={pending} onClose={onClose} submit={() => name && slug && onSave({ name, slug, parent_id: idValue(parent) })} /></Modal> }
function TaskDialog({ open, members, pending, onClose, onSave }: DialogProps & { members: Member[] }) { const [title, setTitle] = useState(""), [description, setDescription] = useState(""), [owner, setOwner] = useState(""), [priority, setPriority] = useState("0"), [dueAt, setDueAt] = useState(""); useEffect(() => { if (open) { setTitle(""); setDescription(""); setOwner(""); setPriority("0"); setDueAt("") } }, [open]); return <Modal open={open} title="新建并分派任务" onClose={onClose}><div className="space-y-3"><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="任务标题" /><textarea className="min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="目标、交付物、验收标准与背景说明" /><div className="grid gap-3 sm:grid-cols-2"><select className={selectClass} value={priority} onChange={(e) => setPriority(e.target.value)}><option value="0">普通优先级</option><option value="1">低优先级</option><option value="2">较低优先级</option><option value="3">中优先级</option><option value="4">高优先级</option><option value="5">紧急</option></select><Input type="datetime-local" value={dueAt} onChange={(e) => setDueAt(e.target.value)} /></div><select className={selectClass} value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">当前管理员作为负责人</option>{members.filter((m) => m.status === "active").map((m) => <option key={m.id} value={m.user_id}>{memberName(m)}</option>)}</select></div><Footer pending={pending} onClose={onClose} submit={() => title.trim() && onSave({ title, description, owner_user_id: idValue(owner), priority: Number(priority), due_at: dueAt ? new Date(dueAt).toISOString() : undefined })} /></Modal> }
function DeviceDialog({ open, members, pending, onClose, onSave }: DialogProps & { members: Member[] }) { const [name, setName] = useState(""), [owner, setOwner] = useState(""), [mode, setMode] = useState("platform"), [port, setPort] = useState("8080"); return <Modal open={open} title="生成企业连接命令" onClose={onClose}><div className="space-y-3"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="设备名称" /><select className={selectClass} value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">当前管理员作为设备负责人</option>{members.filter((m) => m.status === "active").map((m) => <option key={m.id} value={m.user_id}>{memberName(m)}</option>)}</select><select className={selectClass} value={mode} onChange={(e) => setMode(e.target.value)}><option value="platform">标准连接器</option><option value="web_server">站点连接器</option></select>{mode === "web_server" && <Input value={port} onChange={(e) => setPort(e.target.value)} inputMode="numeric" placeholder="站点端口" />}</div><Footer pending={pending} onClose={onClose} submit={() => name.trim() && onSave({ name, owner_user_id: idValue(owner), mode, listen_port: mode === "web_server" ? Number(port) || 8080 : 0 })} /></Modal> }
function ConnectorCommandDialog({ open, command, onClose }: { open: boolean; command: ConnectorCommand | null; onClose: () => void }) { const baseURL = typeof window === "undefined" ? "http://localhost:8080" : window.location.origin; const args = command?.mode === "web_server" ? ` -mode web_server -web-port ${command.listen_port || 8080}` : ""; const windows = command ? `app.exe -server ${quoteCommandArg(baseURL)} -token ${quoteCommandArg(command.token)}${args}` : ""; const unix = command ? `./app -server ${quoteCommandArg(baseURL)} -token ${quoteCommandArg(command.token)}${args}` : ""; const copy = async (value: string) => { if (value) await navigator.clipboard.writeText(value) }; return <Modal open={open} title="企业连接命令" onClose={onClose}><div className="space-y-4"><p className="text-sm text-muted-foreground">在目标设备运行以下命令。令牌仅此时展示，重新生成会使旧命令失效。</p><CommandLine label="Windows" value={windows} onCopy={() => void copy(windows)} /><CommandLine label="macOS / Linux" value={unix} onCopy={() => void copy(unix)} /></div><DialogFooter><Button onClick={onClose}>完成</Button></DialogFooter></Modal> }
function SharedPoolDialog({ open, departments, pending, onClose, onSave }: DialogProps & { tasks: Task[]; departments: Department[] }) { const [target, setTarget] = useState(""), [name, setName] = useState(""); return <Modal open={open} title="创建部门共享池" onClose={onClose}><div className="space-y-3"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="共享池名称" /><select className={selectClass} value={target} onChange={(event) => setTarget(event.target.value)}><option value="">选择部门</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><Footer pending={pending} onClose={onClose} submit={() => name.trim() && target && onSave({ name, scope_type: "department", department_id: Number(target) })} /></Modal> }
function ShareResourceDialog({ open, pool, sessions, files, pending, onClose, onSave }: { open: boolean; pool: SharedPool | null; sessions: PersonalResource[]; files: PersonalResource[]; pending: boolean; onClose: () => void; onSave: (type: "sessions" | "files", id: string) => void }) { const [type, setType] = useState<"sessions" | "files">("sessions"), [id, setID] = useState(""); const options = type === "sessions" ? sessions : files; return <Modal open={open} title={`共享到 ${pool?.name || "共享池"}`} onClose={onClose}><div className="space-y-3"><select className={selectClass} value={type} onChange={(event) => { setType(event.target.value as "sessions" | "files"); setID("") }}><option value="sessions">我的会话</option><option value="files">我的文件</option></select><select className={selectClass} value={id} onChange={(event) => setID(event.target.value)}><option value="">选择资源</option>{options.map((item) => <option key={item.id} value={item.id}>{item.title || item.name || item.id}</option>)}</select></div><Footer pending={pending} onClose={onClose} submit={() => id && onSave(type, id)} /></Modal> }
function CommandLine({ label, value, onCopy }: { label: string; value: string; onCopy: () => void }) { return <div className="space-y-1"><div className="flex items-center justify-between text-sm font-medium"><span>{label}</span><Button size="sm" variant="outline" onClick={onCopy}><Copy className="mr-1 h-4 w-4" />复制</Button></div><code className="block break-all rounded-md border bg-muted p-3 text-xs">{value}</code></div> }
function AssignmentDialog({ open, devices, members, departments, tasks, pending, onClose, onSave }: DialogProps & { devices: Device[]; members: Member[]; departments: Department[]; tasks: Task[] }) { const [device, setDevice] = useState(""), [scope, setScope] = useState("user"), [target, setTarget] = useState(""), [tools, setTools] = useState(""); const targets = scope === "task" ? tasks.map((t) => ({ id: t.id, name: t.title })) : scope === "department" ? departments.map((d) => ({ id: d.id, name: d.name })) : members.map((m) => ({ id: m.user_id, name: memberName(m) })); return <Modal open={open} title="分配设备" onClose={onClose}><div className="space-y-3"><select className={selectClass} value={device} onChange={(e) => setDevice(e.target.value)}><option value="">选择设备</option>{devices.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><select className={selectClass} value={scope} onChange={(e) => { setScope(e.target.value); setTarget("") }}><option value="user">分配给员工</option><option value="department">分配给部门</option><option value="task">分配给任务</option></select><select className={selectClass} value={target} onChange={(e) => setTarget(e.target.value)}><option value="">选择目标</option>{targets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input value={tools} onChange={(e) => setTools(e.target.value)} placeholder="允许工具，逗号分隔（可选）" /></div><Footer pending={pending} onClose={onClose} submit={() => device && target && onSave({ device_id: Number(device), [scope === "task" ? "task_id" : scope === "department" ? "department_id" : "user_id"]: Number(target), allowed_tools: tools.split(",").map((x) => x.trim()).filter(Boolean) })} /></Modal> }
function QuotaDialog({ open, pending, onClose, onSave }: DialogProps) { const [limit, setLimit] = useState(""); return <Modal open={open} title="添加组织预算" onClose={onClose}><Input value={limit} onChange={(e) => setLimit(e.target.value)} placeholder="添加预算金额" /><Footer pending={pending} onClose={onClose} submit={() => limit && onSave({ scope_type: "organization", initial_limit: limit })} /></Modal> }
function AllocationDialog({ open, accounts, pending, onClose, onSave }: DialogProps & { accounts: QuotaAccount[] }) { const [parent, setParent] = useState(""), [child, setChild] = useState(""), [amount, setAmount] = useState(""); return <Modal open={open} title="下拨额度" onClose={onClose}><div className="space-y-3"><select className={selectClass} value={parent} onChange={(e) => setParent(e.target.value)}><option value="">来源账户</option>{accounts.map((x) => <option key={x.id} value={x.id}>#{x.id} {x.scope_key}</option>)}</select><select className={selectClass} value={child} onChange={(e) => setChild(e.target.value)}><option value="">目标账户</option>{accounts.map((x) => <option key={x.id} value={x.id}>#{x.id} {x.scope_key}</option>)}</select><Input value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="额度数量" /></div><Footer pending={pending} onClose={onClose} submit={() => parent && child && amount && onSave({ parent_account_id: Number(parent), child_account_id: Number(child), amount })} /></Modal> }
function PoolBudgetDialog({ open, pools, pending, onClose, onSave, title }: DialogProps & { pools: QuotaAccount[]; title: string }) { const [pool, setPool] = useState(""), [amount, setAmount] = useState(""); return <Modal open={open} title={title} onClose={onClose}><div className="space-y-3"><select className={selectClass} value={pool} onChange={(e) => setPool(e.target.value)}><option value="">选择任务池</option>{pools.map((x) => <option key={x.id} value={x.pool_id}>#{x.id} {x.scope_key}</option>)}</select><Input value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="回收预算" /></div><Footer pending={pending} onClose={onClose} submit={() => pool && amount && onSave({ pool_id: Number(pool), amount })} /></Modal> }
function UserBudgetDialog({ open, members, pending, onClose, onSave }: DialogProps & { members: Member[] }) { const [user, setUser] = useState(""), [amount, setAmount] = useState(""); return <Modal open={open} title="发放组织预算给员工" onClose={onClose}><div className="space-y-3"><select className={selectClass} value={user} onChange={(e) => setUser(e.target.value)}><option value="">选择员工</option>{members.filter((m) => m.status === "active").map((m) => <option key={m.id} value={m.user_id}>{memberName(m)}</option>)}</select><Input value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="发放预算" /></div><Footer pending={pending} onClose={onClose} submit={() => user && amount && onSave({ user_id: Number(user), amount })} /></Modal> }
function RoleDialog({ open, role, permissions, pending, onClose, onSave }: DialogProps & { role: Role | null; permissions: Permission[] }) { const [name, setName] = useState(""), [slug, setSlug] = useState(""), [selected, setSelected] = useState<string[]>([]), [picker, setPicker] = useState(false), [resource, setResource] = useState(""), [code, setCode] = useState(""); useEffect(() => { setName(role?.name || ""); setSlug(role?.slug || ""); setSelected(role?.permissions || []); setPicker(false); setResource(""); setCode("") }, [role, open]); const choices = permissions.filter((item) => item.resource === resource); const add = () => { const codes = code === "__all__" ? choices.map((item) => item.code) : [code]; setSelected((value) => [...new Set([...value, ...codes.filter(Boolean)])]); setPicker(false); setResource(""); setCode("") }; return <><Modal open={open} title={role ? "编辑自定义权限组" : "新建自定义权限组"} onClose={onClose}><div className="space-y-3"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="权限组名称" /><Input disabled={Boolean(role)} value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="权限组标识，例如 project-manager" /><div className="rounded-md border p-3"><div className="mb-2 flex items-center justify-between text-sm font-medium"><span>已选权限（{selected.length}）</span><Button size="sm" variant="outline" onClick={() => setPicker(true)}><Plus className="mr-1 h-4 w-4" />新增权限</Button></div>{selected.length ? <div className="space-y-1">{selected.map((item) => <div key={item} className="flex items-center justify-between text-sm"><span>{item}</span><Button size="icon" variant="ghost" onClick={() => setSelected((value) => value.filter((entry) => entry !== item))}><Trash2 size={14} /></Button></div>)}</div> : <p className="text-xs text-muted-foreground">尚未分配权限。</p>}</div></div><Footer pending={pending} onClose={onClose} submit={() => name && slug && onSave({ name, slug, permissions: selected })} /></Modal><Dialog open={picker} onOpenChange={setPicker}><DialogContent><DialogHeader><DialogTitle>新增权限</DialogTitle></DialogHeader><div className="space-y-3"><select className={selectClass} value={resource} onChange={(e) => { setResource(e.target.value); setCode("") }}><option value="">选择权限分类</option>{[...new Set(permissions.map((item) => item.resource))].map((item) => <option key={item} value={item}>{item}</option>)}</select><select className={selectClass} value={code} disabled={!resource} onChange={(e) => setCode(e.target.value)}><option value="">选择具体权限</option>{resource && <option value="__all__">全部（{resource}）</option>}{choices.map((item) => <option key={item.code} value={item.code}>{item.code}{item.description ? ` · ${item.description}` : ""}</option>)}</select></div><DialogFooter><Button variant="outline" onClick={() => setPicker(false)}>取消</Button><Button disabled={!code} onClick={add}>添加权限</Button></DialogFooter></DialogContent></Dialog></> }
function BindingDialog({ open, members, roles, pending, onClose, onSave }: DialogProps & { members: Member[]; roles: Role[] }) { const [user, setUser] = useState(""), [role, setRole] = useState(""); return <Modal open={open} title="授予员工角色" onClose={onClose}><div className="space-y-3"><select className={selectClass} value={user} onChange={(e) => setUser(e.target.value)}><option value="">选择员工</option>{members.map((m) => <option key={m.id} value={m.user_id}>{memberName(m)}</option>)}</select><select className={selectClass} value={role} onChange={(e) => setRole(e.target.value)}><option value="">选择角色</option>{roles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></div><Footer pending={pending} onClose={onClose} submit={() => user && role && onSave({ user_id: Number(user), role_id: Number(role), scope_type: "organization", scope_id: 0 })} /></Modal> }
function HeaderAction({ label, onClick, disabled }: { label: string; onClick?: () => void; disabled?: boolean }) { return <Button size="sm" disabled={disabled} onClick={onClick}><Plus className="mr-1 h-4 w-4" />{label}</Button> }
function Section({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle><p className="text-sm text-muted-foreground">{description}</p></CardHeader><CardContent>{children}</CardContent></Card> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md border p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 truncate text-lg font-semibold">{value}</div></div> }
function Row({ title, detail }: { title: string; detail: string }) { return <div className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3"><span className="font-medium">{title}</span><span className="text-xs text-muted-foreground">{detail}</span></div> }
function Empty({ text }: { text: string }) { return <div className="rounded-md border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</div> }
function memberName(member: Member) { return member.user?.username || member.user?.email || "未知用户" }
function userName(user: User | undefined, userID: number) { return user?.username || user?.email || `用户 ${userID}` }
function idValue(value: string) { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : undefined }
function quoteCommandArg(value: string) { return `"${value.replace(/"/g, '\\"')}"` }
function apiError(value: unknown) { const err = value as { response?: { data?: { error?: string } }; message?: string }; return err.response?.data?.error || err.message || "操作失败，请稍后重试" }
type DialogProps = { open: boolean; pending: boolean; onClose: () => void; onSave: (body: object) => void }
type EnterpriseTab = "organization" | "members" | "tasks" | "pools" | "devices" | "quota" | "security"
